import {TrajetsCollection} from '../trajet/trajet.interface';

export const STATIONS: TrajetsCollection[] = [
  {id: 22, name: 'Mairie d’Aubervilliers', value: "mairie+d'aubervilliers"},
  {id: 21, name: 'André Karman', value: 'andre+karman'},
  {id: 20, name: 'Villebois-Mareuil', value: 'villebois+++mareuil'},
  {id: 19, name: 'Félix Faure-Victor Hugo', value: 'felix+faure+++victor+hugo'},
  {id: 18, name: 'Gardinoux', value: 'gardinoux'},
  {id: 17, name: 'La Haie Coq', value: 'la+haie+coq'},
  {id: 16, name: 'Parc du millénaire', value: 'parc+du+millenaire'},
  {id: 15, name: 'Skanderbeg', value: 'skanderbeg'},
  {id: 14, name: 'Porte d’Aubervilliers-Cité Ch.Hermite', value: "porte+d'aubervilliers+++cite+ch.+hermite"},
  {id: 13, name: 'Porte d’Aubervilliers-Macdonald', value: "porte+d'aubervilliers+++macdonald"},
  {id: 12, name: 'Évangile-Aubervilliers', value: 'evangile+++aubervilliers'},
  {id: 11, name: 'Tristan Tzara', value: 'tristan+tzara'},
  {id: 10, name: 'Place Hébert', value: 'place+hebert'},
  {id: 9, name: 'Place de Torcy', value: 'place+de+torcy'},
  {id: 8, name: 'Ordener-Marx Dormoy', value: 'ordener+++marx+dormoy'},
  {id: 7, name: 'Département-Marx Dormoy', value: 'departement+++marx+dormoy'},
  {id: 6, name: 'Place de la Chapelle', value: 'place+de+la+chapelle'},
  {id: 5, name: 'Cail-Demarquay', value: 'cail+++demarquay'},
  {id: 4, name: 'Gare du Nord', value: 'gare+du+nord'},
  {id: 3, name: 'La Fayette-Dunkerque', value: 'la+fayette+++dunkerque'},
  {id: 2, name: 'Valenciennes', value: 'valenciennes'},
  {id: 1, name: 'Gare de l’Est', value: "gare+de+l'est."},
];
